default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: TXLJNDH-DT93969        #   Snowflake account identifier
      user: KGARACHH                      
      password: Pitmpitm@12345              
      database: DBT_SF_DB                  
      schema: DBT_SF_SC                  
      warehouse: compute_wh               
      threads: 4
